blog/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.views.static import serve
from checkout import urls as urls_checkout
from .settings import MEDIA_ROOT
from . import views
from .views import index, home, diary, predict, henry, jose
from checkout import views as checkout_views
from checkout.views import predict

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^diary/$', views.diary, name="diary"),
    url(r'^henry/$', henry, name="henry"),
    url(r'^jose/$', jose, name="jose"),
    url(r'^predict/', checkout_views.predict),
    url(r'checkout/', include('checkout.urls')),
    url(r'^posts/', include('posts.urls')),
]

posts/urls.py
from django.conf.urls import url
from .views import get_posts, add_comment, post_detail,  new_post, edit_post


urlpatterns = [
    url(r'^$', get_posts, name="get_posts"),
    url(r'^(?P<pk>\d+)/add_comment/$', add_comment, name='add_comment'),
    url(r'^(?P<pk>\d+)/$', post_detail, name='post_detail'),
    url(r'^new/$', new_post, name='new_post'),
    url(r'^(?P<pk>\d+)/edit/$', edit_post, name='edit_post')
]

urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from blog import urls as urls_blog
from blog import views as v
from search import urls as urls_search
from checkout import urls as urls_checkout
from django.views import static
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', v.index),
    url(r'^blog/', include( include('blog.urls')),
    url(r'^/checkout/', include(urls_checkout)),
    url(r'^posts/', include('posts.urls')),
    url(r'^media/(?P<path>.*)$', static.serve,{'document_root': MEDIA_ROOT}),
    
]

posts/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    """
    A single Blog post
    """
    title = models.CharField(max_length=200)
    user = models.CharField(max_length=200, null=True)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True, default=timezone.now)
    views = models.IntegerField(default=0)
    tag = models.CharField(max_length=30, blank=True, null=True)
    image = models.ImageField(upload_to="img", blank=True, null=True)
    
    def __unicode__(self):
        return self.title
    

class Entry(models.Model):
    comment = models.ForeignKey(Post, on_delete=None)
    user = models.CharField(max_length=200, null=True)
    body = models.TextField(max_length=500, null=True, default=None)
    date_posted = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return 'Entry #{}'.format(self.id)

    class Meta:
        verbose_name_plural = 'entries'   

posts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Entry

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ('user', 'body', )
 
class BlogPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image', 'tag', 'published_date',)
        

posts/views.py
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from django.conf import settings
from django.contrib import messages
from django.utils import timezone
from .models import Post, Entry
from .forms import BlogPostForm, EntryForm

# Create your views here.
def get_posts(request):
    """
    Create a view that will return a
    list of Posts that were published prior to'now'
    and render them to the 'blogposts.html' template
    """
    posts = Post.objects.filter(published_date__lte=timezone.now
        ()).order_by('-published_date')
    return render(request, "blogposts.html", {'posts': posts})


def add_comment(request, pk):
    post_reference = get_object_or_404(Post, pk=pk)
    entry = Entry()
    
    if request.method == 'POST':
        form = EntryForm(request.POST, request.FILES)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment = post_reference
            comment.save()
            return redirect(post_detail, pk)
    else:
        form = EntryForm()

    return render(request, 'add.html', {'form': form, 'entry': entry})
    

def post_detail(request, pk):
    """
    Create a view that returns a single
    Post object based on the post ID (pk) and
    render it to the 'postdetail.html' template.
    Or return a 404 error if the post is 
    not found
    """
    post = get_object_or_404(Post, pk=pk)
    post.views += 1
    post.save()
    entry = Entry.objects.filter(comment=pk)
    
    return render(request, "postdetail.html", {'post': post, 'entry': entry})


def new_post(request):
    template = 'blogpostform.html'
    form = BlogPostForm(request.POST or None)
    
    try:
        if form.is_valid():
            title = request.POST.get('title', '')
            content = request.POST.get('content', '')
            image = request.POST.get('image', '')
            tag = request.POST.get('tag', '')
            published_date = request.POST.get('published_date', '')
            form.save()
            print(messages.success)
            messages.success(request, 'Blog post was saved to the database')
    except Exception as e:
        messages.warning(request, 'Blog post was not saved. Error: {}'. format(e))
        
    else:
        form = BlogPostForm()
        
    context = {'form': form,}
    return render(request, template, context)
    
    
def edit_post(request, pk=None):
    """
    Create a view that allows us to edit a post
    object depending if the post ID is null or not 
    """
    post = get_object_or_404(Post, pk=pk) if pk else None
    if request.method == "POST":
        form = BlogPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect(post_detail, post.pk)
    else:
        form = BlogPostForm(instance=post)
    return render(request, 'blogpostform.html', {'form' : form})
    
    
    

    

posts/templates/add.html
{% extends 'base.html' %}
{% block content %}
<h1></h1>
<body>

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <h2 class-"form-commentadd-heading">Add your Comments</h2>
        <div class="form-group">
            <label for="inputName" class="sr-only">Name</label>
            <input type="text" id="id_user" name="user" class="form-control" placeholder="Name" required autofocus>
        </div>
            <div class="comment-group">
                <textarea name="body" id="body"></textarea>
                
            </div>
        <button class="btn btn-sm btn-primary btn-info" type="submit">Submit</button>
    </form>
</div>
</body>
{% endblock %}
    

posts/templates/blogpostform.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% block content %}
    <h1>New Post</h1>
    <form method="POST">{% csrf_token %}
        {{ form | as_bootstrap }}
        <button type="submit" class="btn btn-info">Save</button>
    </form>
{% endblock %}

posts/templates/blogposts.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <a href="{% url 'new_post' %}" class="btn btn-default">New Post</a>
    </div>
    {% for post in posts %} 
        <div class="row">
            <div class="col-md-10 col-sm-9">
                <h3>{{ post.title }}</h3>
                <div class="row">
                    <div class="col-xs-9">
                        <tr>{{ post.content|truncatewords:30 }}</tr>
                        <a href="{% url 'post_detail' post.id %}" class="btn btn-default">Read more</a>
                        <li>Author: Lee</li>
                        <li>Published on:</span> {{ post.published_date }}</li>
                        <li>Views: {{ post.views }}</li>
                        <li>Tag: {{ post.tag }}</li>
                    </div>
                </div>
            </div>
            <hr>
        </div>
    {% endfor %}
{% endblock %}

posts/templates/postdetail.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-10 col-sm-9">
          {% if post.image %}
              <img class="img-blogpost" src="/media/{{ post.image }}">
          {% endif %}
          <h3>{{ post.title }}</h3>
            <div class="row">
              <div class="col-xs-9">
                <br>{{ post.content }}
                <br>Author: Lee
                <br>Published on: {{ post.published_date }}
                <br>Views: {{ post.views }}
                <br>Tag: {{ post.tag }}</br>
                <a href="{% url 'get_posts' %}" class="btn btn-default">Back to Post</a>
                <a href="{% url 'edit_post' post.id %}" class="btn btn-default">Edit Post</a>
                <hr>
              </div>
                <section class="section">
                  <div class="container">
                    <div class="media-content">
                      <div class="content">
                        <a type="button" class="btn btn-link" href="{% url 'add_comment' post.id %}">Get involved with your Comments</a>
                        
                        <div class="main-comment-section">
                          {% for item in entry %}
                            <br><i>{{ item.date_posted }}</i>
                            <br><strong>{{ item.user }}</strong>
                            <br><strong>{{ item.body }}</strong></br>
                        {% empty %}
                            <p>There is no comments!</p>
                          </div>
                      </div>
                    </div>
                  </div>
                      {% endfor %}
                  </section>
              </div>
          </div>
      </div>
{% endblock %}